Andrew Naysmith 
Alliance Media Group

732-845-4902

Billboard availability Ridge Road near Sacred Heart School wanted to know it you want 1200 (4 weeks).

Printed and installed for 1500 + 1200 4 weeks

Minimimum 3 periods 