[[redirects]]
  from = "/why-your-company-needs-an-api/"
  to = " /post/why-your-company-needs-an-API/"
  status = 301
  force = true

[[redirects]]
  from = "/why-your-company-needs-an-API/"
  to = " /post/why-your-company-needs-an-API/"
  status = 301
  force = true

[[redirects]]
  from = "/what-are-googles-web-vitals/"
  to = " /post/what-are-googles-web-vitals/"
  status = 301
  force = true

[[redirects]]
  from = "/we-are-a-jamstack-shop/"
  to = " /post/we-are-a-jamstack-shop/"
  status = 301
  force = true

[[redirects]]
  from = "/make-your-company-a-pwa/"
  to = " /post/make-your-company-a-pwa/"
  status = 301
  force = true

[[redirects]]
  from = "/use-wordpress-for-what-it-is-best-at/"
  to = " /post/use-wordpress-for-what-it-is-best-at/"
  status = 301
  force = true

[[redirects]]
  from = "/what-are-googles-web-vitals/"
  to = " /post/what-are-googles-web-vitals/"
  status = 301
  force = true

[[redirects]]
  from = "/post/what-are-googles-web-vitals/"
  to = " /post/googles-metrics-on-exceptional-web-page-experience/"
  status = 301
  force = true

[[redirects]]
  from = "/post/web-vitals-largest-contentful-paint/"
  to = " /post/why-does-large-content-on-a-web-page-so-slow/"
  status = 301
  force = true

[[redirects]]
  from = "/post/how-to-paint-a-webpage-faster/"
  to = "/post/load-important-content-on-your-web-page-faster/"
  status = 301
  force = true

[[redirects]]
  from = "/post/web-vitals-cumulative-layout-shift/"
  to = "/post/why-do-page-elements-move-all-of-a-sudden"
  status = 301
  force = true